source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/yunhaiwu/ios-wj-framework-cocoapods-specs.git'

platform :ios, '8.0'

inhibit_all_warnings!

#use_frameworks!

target :'CocoaService-HttpService-example' do

pod 'CocoaService'
#pod 'CSHttpServiceAPI', :path => '../../'

end
